### ISSUE TITLE
scm->json verification

### ISSUE THREAD

**Issue by johnwcowan** [amirouche/SRFI-JSON#3]
It should be a requirement on `scm->json` that if the *obj* argument is not a valid representation of JSON, that it outputs nothing.  This implies calling a validity checker before starting to output.  If the output is not valid, signal an error that satisfies a new predicate `json-error?`.

**Comment by amirouche** [comment]
done in https://github.com/amirouche/SRFI-JSON/commit/1de7bdcab3b0bad379342a01b9ff79468c6931e4
